/* TYPES FOR CHARACTERS */
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCSESS = "FETCH_CHARACTERS_SUCCSESS";
export const FETCH_CHARACTER_UPDATE_SUCCSESS = "FETCH_CHARACTER_UPDATE_SUCCSESS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";

export const FETCH_CHARACTERS_BY_NAME_START = "FETCH_CHARACTERS_BY_NAME_START";
export const FETCH_CHARACTERS_BY_NAME_SUCCSESS = "FETCH_CHARACTERS_BY_NAME_SUCCSESS";
export const FETCH_CHARACTERS_BY_NAME_FAIL = "FETCH_CHARACTERS_BY_NAME_FAIL";

/* TYPES FOR CHARACTER SERIES */
export const FETCH_SERIES_START = "FETCH_SERIES_START";
export const FETCH_SERIES_SUCCSESS = "FETCH_SERIES_SUCCSESS";
export const FETCH_SERIES_FAIL = "FETCH_SERIES_FAIL";

/* TYPES FOR FAVORITES */
export const TOGGLE_FAVORITES = "TOGGLE_FAVORITES"
export const LOAD_FAVORITES = "LOAD_FAVORITES"