/* TYPES FOR CHARACTERS */
export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START";
export const FETCH_CHARACTERS_SUCCSESS = "FETCH_CHARACTERS_SUCCSESS";
export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTERS_FAIL = "FETCH_CHARACTERS_FAIL";

export const FETCH_CHARACTER_UPDATE = "FETCH_CHARACTER_UPDATE";
export const FETCH_CHARACTER_UPDATE_SUCCSESS = "FETCH_CHARACTER_UPDATE_SUCCSESS";

export const FETCH_CHARACTER_BY_ID = "FETCH_CHARACTER_BY_ID";
export const FETCH_CHARACTER_BY_ID_SUCCSESS = "FETCH_CHARACTER_BY_ID_SUCCSESS";
export const FETCH_CHARACTER_BY_ID_FAIL = "FETCH_CHARACTER_BY_ID_FAIL";

export const FETCH_CHARACTERS_BY_NAME = "FETCH_CHARACTERS_BY_NAME";
export const FETCH_CHARACTERS_BY_NAME_START = "FETCH_CHARACTERS_BY_NAME_START";
export const FETCH_CHARACTERS_BY_NAME_SUCCSESS = "FETCH_CHARACTERS_BY_NAME_SUCCSESS";
export const FETCH_CHARACTERS_BY_NAME_FAIL = "FETCH_CHARACTERS_BY_NAME_FAIL";

/* TYPES FOR CHARACTER SERIES */
export const FETCH_SERIES = "FETCH_SERIES";
export const FETCH_SERIES_START = "FETCH_SERIES_START";
export const FETCH_SERIES_SUCCSESS = "FETCH_SERIES_SUCCSESS";
export const FETCH_SERIES_FAIL = "FETCH_SERIES_FAIL";

/* TYPES FOR FAVORITES */
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE"
export const TOGGLE_FAVORITE_SUCCESS = "TOGGLE_FAVORITE_SUCCESS"
export const LOAD_FAVORITES = "LOAD_FAVORITES"
export const LOAD_FAVORITES_SUCCESS = "LOAD_FAVORITES_SUCCESS"